# Generated by Django 4.2.4 on 2023-08-29 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Musicia',
            new_name='Musician',
        ),
    ]
