# Generated by Django 4.2.4 on 2023-09-06 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_alter_album_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='album',
            table=None,
        ),
    ]
